version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
    links:
      - backend
    depends_on:
      - backend

networks:
  default:
    external:
      name: ${MONGO_CONTAINER_NETWORK}
